{
    'name': 'DCR',
    'version': '19.0.6.0.0',
    'category': 'Innovative',
    'summary': 'Daily Call Report with Cross-Reference Opportunities',
    'description': 'DCR form with customer info, visit purpose, cross-reference, competitor insights, follow-up actions, and attachments.',
    'author': 'IEPPL - Reliution',
    'license': 'AGPL-3',
    'depends': ['base', 'sale_crm', 'contacts', 'sale_customization', 'ieppl_product_customization', "helpdesk_mgmt",
                "web", "hr_expense"],
    'sequence': 1,
    "data": [
        "security/ir.model.access.csv",
        "data/dcr_form_demo.xml",
        "data/surface_data.xml",
        "data/operations_data.xml",
        "report/loctite_trial_report_template.xml",
        "views/dcr_master_views.xml",
        "views/product_application_views.xml",
        "views/crm_lead_views.xml",
        "views/crm_lead_line_views.xml",
        "views/helpdesk_ticket.xml",
        "views/master_views.xml",
        "views/res_partner.xml",
        "views/trial_report_line.xml",
        'views/trial_report_view.xml',
],
    "installable": True,
    "application": False,
    "images": ['static/description/dcr.png']
}
