from . import product_application
from . import dcr_cross_ref
from . import dcr_master
from . import crm_lead_line
from . import crm_lead
from . import helpdesk_ticket
from . import fuchs_masters
from . import res_partner
from . import trial_report
